version: '3'

services:
  app:
    build:
      dockerfile: build/dev/Dockerfile
    container_name: b-day-challenge
    ports:
      - 443:443
    volumes:
      - .:/app/
      - ./upload:/www-data/
    env_file:
      - ./build/dev/example.env
    networks:
      - database_default
networks:
  database_default:
    external: true

